// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document_share.sql

package sqlc

import (
	"context"
)

const createShare = `-- name: CreateShare :one
INSERT INTO document_share (id, document_id, shared_with_user_id, permission)
VALUES ($1, $2, $3, $4)
ON CONFLICT (document_id, shared_with_user_id)
DO UPDATE SET permission = EXCLUDED.permission
RETURNING id, document_id, shared_with_user_id, permission, created_at
`

type CreateShareParams struct {
	ID               string `json:"id"`
	DocumentID       string `json:"document_id"`
	SharedWithUserID string `json:"shared_with_user_id"`
	Permission       string `json:"permission"`
}

func (q *Queries) CreateShare(ctx context.Context, arg CreateShareParams) (DocumentShare, error) {
	row := q.db.QueryRow(ctx, createShare,
		arg.ID,
		arg.DocumentID,
		arg.SharedWithUserID,
		arg.Permission,
	)
	var i DocumentShare
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.SharedWithUserID,
		&i.Permission,
		&i.CreatedAt,
	)
	return i, err
}

const deleteShare = `-- name: DeleteShare :exec
DELETE FROM document_share
WHERE document_id = $1 AND shared_with_user_id = $2
`

type DeleteShareParams struct {
	DocumentID       string `json:"document_id"`
	SharedWithUserID string `json:"shared_with_user_id"`
}

func (q *Queries) DeleteShare(ctx context.Context, arg DeleteShareParams) error {
	_, err := q.db.Exec(ctx, deleteShare, arg.DocumentID, arg.SharedWithUserID)
	return err
}

const getShare = `-- name: GetShare :one
SELECT id, document_id, shared_with_user_id, permission, created_at
FROM document_share
WHERE document_id = $1 AND shared_with_user_id = $2
`

type GetShareParams struct {
	DocumentID       string `json:"document_id"`
	SharedWithUserID string `json:"shared_with_user_id"`
}

func (q *Queries) GetShare(ctx context.Context, arg GetShareParams) (DocumentShare, error) {
	row := q.db.QueryRow(ctx, getShare, arg.DocumentID, arg.SharedWithUserID)
	var i DocumentShare
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.SharedWithUserID,
		&i.Permission,
		&i.CreatedAt,
	)
	return i, err
}

const listDocumentsSharedWith = `-- name: ListDocumentsSharedWith :many
SELECT d.id, d.user_id, d.title, d.mode, d.page_count, d.status, d.created_at
FROM document d
JOIN document_share s ON s.document_id = d.id
WHERE s.shared_with_user_id = $1
ORDER BY d.created_at DESC
`

func (q *Queries) ListDocumentsSharedWith(ctx context.Context, sharedWithUserID string) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsSharedWith, sharedWithUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Mode,
			&i.PageCount,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharesForDocument = `-- name: ListSharesForDocument :many
SELECT id, document_id, shared_with_user_id, permission, created_at
FROM document_share
WHERE document_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListSharesForDocument(ctx context.Context, documentID string) ([]DocumentShare, error) {
	rows, err := q.db.Query(ctx, listSharesForDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentShare
	for rows.Next() {
		var i DocumentShare
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.SharedWithUserID,
			&i.Permission,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
