// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document.sql

package sqlc

import (
	"context"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO document (id, user_id, title, mode)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, title, mode, page_count, status, created_at
`

type CreateDocumentParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
	Title  string `json:"title"`
	Mode   string `json:"mode"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Mode,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Mode,
		&i.PageCount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getDocument = `-- name: GetDocument :one
SELECT id, user_id, title, mode, page_count, status, created_at
FROM document
WHERE id = $1
`

func (q *Queries) GetDocument(ctx context.Context, id string) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Mode,
		&i.PageCount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const incrementDocumentPageCount = `-- name: IncrementDocumentPageCount :one
UPDATE document SET page_count = page_count + 1 WHERE id = $1 RETURNING page_count
`

func (q *Queries) IncrementDocumentPageCount(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRow(ctx, incrementDocumentPageCount, id)
	var page_count int32
	err := row.Scan(&page_count)
	return page_count, err
}

const listDocumentsByUser = `-- name: ListDocumentsByUser :many
SELECT id, user_id, title, mode, page_count, status, created_at
FROM document
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDocumentsByUser(ctx context.Context, userID string) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Mode,
			&i.PageCount,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDocumentStatus = `-- name: SetDocumentStatus :exec
UPDATE document SET status = $2 WHERE id = $1
`

type SetDocumentStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) SetDocumentStatus(ctx context.Context, arg SetDocumentStatusParams) error {
	_, err := q.db.Exec(ctx, setDocumentStatus, arg.ID, arg.Status)
	return err
}
