// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EmailVerification struct {
	ID         string             `json:"id"`
	UserID     string             `json:"user_id"`
	CodeHash   string             `json:"code_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	Attempts   int32              `json:"attempts"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID               string             `json:"id"`
	UserID           string             `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
}

type WebUser struct {
	ID            string             `json:"id"`
	Username      string             `json:"username"`
	Email         string             `json:"email"`
	PasswordHash  string             `json:"password_hash"`
	Role          string             `json:"role"`
	EmailVerified bool               `json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}
