// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ocr.sql

package sqlc

import (
	"context"
)

const createOCRResult = `-- name: CreateOCRResult :one
INSERT INTO ocr_result (id, page_id, model, text, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, page_id, model, text, status, created_at
`

type CreateOCRResultParams struct {
	ID     string `json:"id"`
	PageID string `json:"page_id"`
	Model  string `json:"model"`
	Text   string `json:"text"`
	Status string `json:"status"`
}

func (q *Queries) CreateOCRResult(ctx context.Context, arg CreateOCRResultParams) (OcrResult, error) {
	row := q.db.QueryRow(ctx, createOCRResult,
		arg.ID,
		arg.PageID,
		arg.Model,
		arg.Text,
		arg.Status,
	)
	var i OcrResult
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Model,
		&i.Text,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestOCRResult = `-- name: GetLatestOCRResult :one
SELECT id, page_id, model, text, status, created_at
FROM ocr_result
WHERE page_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestOCRResult(ctx context.Context, pageID string) (OcrResult, error) {
	row := q.db.QueryRow(ctx, getLatestOCRResult, pageID)
	var i OcrResult
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Model,
		&i.Text,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
