// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: output.sql

package sqlc

import (
	"context"
)

const createOutput = `-- name: CreateOutput :one
INSERT INTO output (id, user_id, document_id, template_id, content, file_path, model, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, document_id, template_id, content, file_path, model, status, created_at
`

type CreateOutputParams struct {
	ID         string  `json:"id"`
	UserID     string  `json:"user_id"`
	DocumentID string  `json:"document_id"`
	TemplateID string  `json:"template_id"`
	Content    string  `json:"content"`
	FilePath   *string `json:"file_path"`
	Model      string  `json:"model"`
	Status     string  `json:"status"`
}

func (q *Queries) CreateOutput(ctx context.Context, arg CreateOutputParams) (Output, error) {
	row := q.db.QueryRow(ctx, createOutput,
		arg.ID,
		arg.UserID,
		arg.DocumentID,
		arg.TemplateID,
		arg.Content,
		arg.FilePath,
		arg.Model,
		arg.Status,
	)
	var i Output
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DocumentID,
		&i.TemplateID,
		&i.Content,
		&i.FilePath,
		&i.Model,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getOutput = `-- name: GetOutput :one
SELECT id, user_id, document_id, template_id, content, file_path, model, status, created_at
FROM output
WHERE id = $1
`

func (q *Queries) GetOutput(ctx context.Context, id string) (Output, error) {
	row := q.db.QueryRow(ctx, getOutput, id)
	var i Output
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DocumentID,
		&i.TemplateID,
		&i.Content,
		&i.FilePath,
		&i.Model,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listOutputsByDocument = `-- name: ListOutputsByDocument :many
SELECT id, user_id, document_id, template_id, content, file_path, model, status, created_at
FROM output
WHERE document_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOutputsByDocument(ctx context.Context, documentID string) ([]Output, error) {
	rows, err := q.db.Query(ctx, listOutputsByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Output
	for rows.Next() {
		var i Output
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DocumentID,
			&i.TemplateID,
			&i.Content,
			&i.FilePath,
			&i.Model,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
