// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: page.sql

package sqlc

import (
	"context"
)

const clearPageImage = `-- name: ClearPageImage :exec
UPDATE page SET image_path = NULL, thumb_path = NULL WHERE id = $1
`

func (q *Queries) ClearPageImage(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, clearPageImage, id)
	return err
}

const createPage = `-- name: CreatePage :one
INSERT INTO page (id, document_id, page_number, image_path, thumb_path, width, height, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, document_id, page_number, image_path, thumb_path, width, height, status
`

type CreatePageParams struct {
	ID         string  `json:"id"`
	DocumentID string  `json:"document_id"`
	PageNumber int32   `json:"page_number"`
	ImagePath  *string `json:"image_path"`
	ThumbPath  *string `json:"thumb_path"`
	Width      int32   `json:"width"`
	Height     int32   `json:"height"`
	Status     string  `json:"status"`
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (Page, error) {
	row := q.db.QueryRow(ctx, createPage,
		arg.ID,
		arg.DocumentID,
		arg.PageNumber,
		arg.ImagePath,
		arg.ThumbPath,
		arg.Width,
		arg.Height,
		arg.Status,
	)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.PageNumber,
		&i.ImagePath,
		&i.ThumbPath,
		&i.Width,
		&i.Height,
		&i.Status,
	)
	return i, err
}

const getPageByNumber = `-- name: GetPageByNumber :one
SELECT id, document_id, page_number, image_path, thumb_path, width, height, status
FROM page
WHERE document_id = $1 AND page_number = $2
`

type GetPageByNumberParams struct {
	DocumentID string `json:"document_id"`
	PageNumber int32  `json:"page_number"`
}

func (q *Queries) GetPageByNumber(ctx context.Context, arg GetPageByNumberParams) (Page, error) {
	row := q.db.QueryRow(ctx, getPageByNumber, arg.DocumentID, arg.PageNumber)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.PageNumber,
		&i.ImagePath,
		&i.ThumbPath,
		&i.Width,
		&i.Height,
		&i.Status,
	)
	return i, err
}

const listPagesByDocument = `-- name: ListPagesByDocument :many
SELECT id, document_id, page_number, image_path, thumb_path, width, height, status
FROM page
WHERE document_id = $1
ORDER BY page_number ASC
`

func (q *Queries) ListPagesByDocument(ctx context.Context, documentID string) ([]Page, error) {
	rows, err := q.db.Query(ctx, listPagesByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Page
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.PageNumber,
			&i.ImagePath,
			&i.ThumbPath,
			&i.Width,
			&i.Height,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPageStatus = `-- name: SetPageStatus :exec
UPDATE page SET status = $2 WHERE id = $1
`

type SetPageStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) SetPageStatus(ctx context.Context, arg SetPageStatusParams) error {
	_, err := q.db.Exec(ctx, setPageStatus, arg.ID, arg.Status)
	return err
}
