// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: template.sql

package sqlc

import (
	"context"
)

const getTemplate = `-- name: GetTemplate :one
SELECT id, owner_user_id, name, doc_type_hint, scope, prompt, output_format, json_schema, is_builtin
FROM template
WHERE id = $1
`

func (q *Queries) GetTemplate(ctx context.Context, id string) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplate, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.DocTypeHint,
		&i.Scope,
		&i.Prompt,
		&i.OutputFormat,
		&i.JsonSchema,
		&i.IsBuiltin,
	)
	return i, err
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, owner_user_id, name, doc_type_hint, scope, prompt, output_format, json_schema, is_builtin
FROM template
WHERE is_builtin = true OR owner_user_id IS NOT NULL
ORDER BY is_builtin DESC, name ASC
`

func (q *Queries) ListTemplates(ctx context.Context) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.DocTypeHint,
			&i.Scope,
			&i.Prompt,
			&i.OutputFormat,
			&i.JsonSchema,
			&i.IsBuiltin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
