// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO web_user (id, username, email, password_hash, role)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, email, password_hash, role, email_verified, created_at
`

type CreateUserParams struct {
	ID           string `json:"id"`
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (WebUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
	)
	var i WebUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, role, email_verified, created_at
FROM web_user
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (WebUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i WebUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, role, email_verified, created_at
FROM web_user
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (WebUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i WebUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, role, email_verified, created_at
FROM web_user
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (WebUser, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i WebUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const setUserEmailVerified = `-- name: SetUserEmailVerified :exec
UPDATE web_user
SET email_verified = true
WHERE id = $1
`

func (q *Queries) SetUserEmailVerified(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, setUserEmailVerified, id)
	return err
}
