// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeEmailVerification = `-- name: ConsumeEmailVerification :exec
UPDATE email_verification
SET consumed_at = now()
WHERE id = $1
`

func (q *Queries) ConsumeEmailVerification(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, consumeEmailVerification, id)
	return err
}

const createEmailVerification = `-- name: CreateEmailVerification :one
INSERT INTO email_verification (id, user_id, code_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, code_hash, expires_at, attempts, consumed_at, created_at
`

type CreateEmailVerificationParams struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	CodeHash  string             `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, createEmailVerification,
		arg.ID,
		arg.UserID,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEmailVerificationsByUser = `-- name: DeleteEmailVerificationsByUser :exec
DELETE FROM email_verification
WHERE user_id = $1
`

func (q *Queries) DeleteEmailVerificationsByUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteEmailVerificationsByUser, userID)
	return err
}

const getActiveEmailVerification = `-- name: GetActiveEmailVerification :one
SELECT id, user_id, code_hash, expires_at, attempts, consumed_at, created_at
FROM email_verification
WHERE user_id = $1 AND consumed_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveEmailVerification(ctx context.Context, userID string) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, getActiveEmailVerification, userID)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementVerificationAttempts = `-- name: IncrementVerificationAttempts :one
UPDATE email_verification
SET attempts = attempts + 1
WHERE id = $1
RETURNING attempts
`

func (q *Queries) IncrementVerificationAttempts(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRow(ctx, incrementVerificationAttempts, id)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}
